Repository raiden-network/light-client, pull requests merged in 2019-07, with the labels that each got.

#203 Add README lines about SDK Development docs
  README.md
  raiden/README.md
Labels: Dev: Please Review, sdk 🖥

#202 Some adjustments to Address type and concurrency control for some events
  raiden/src/channels/epics.ts
  raiden/src/utils/types.ts
  raiden/tests/unit/epics.spec.ts
  raiden/tests/unit/utils.spec.ts
Labels: Dev: Please Review, sdk 🖥

#206 Head title changes depending on the page
  raiden-dapp/src/components/AppHeader.vue
  raiden-dapp/src/router.ts
Labels: Dev: Please Review

#207 Update ui
  raiden-dapp/package-lock.json
  raiden-dapp/package.json
  raiden-dapp/src/App.vue
  raiden-dapp/src/assets/back_arrow.svg
  raiden-dapp/src/assets/copy_icon.svg
  raiden-dapp/src/assets/error.png
  raiden-dapp/src/assets/input_invalid.svg
  raiden-dapp/src/assets/input_valid.svg
  raiden-dapp/src/components/AddressInput.vue
  raiden-dapp/src/components/AmountInput.vue
  raiden-dapp/src/components/AppHeader.vue
  raiden-dapp/src/components/ChannelActions.vue
  raiden-dapp/src/components/ChannelDeposit.vue
  raiden-dapp/src/components/ChannelLifeCycle.vue
  raiden-dapp/src/components/ChannelList.vue
  raiden-dapp/src/components/Confirmation.vue
  raiden-dapp/src/components/ConfirmationDialog.vue
  raiden-dapp/src/components/ErrorScreen.vue
  raiden-dapp/src/components/ListHeader.vue
  raiden-dapp/src/components/ProgressOverlay.vue
  raiden-dapp/src/components/Tokens.vue
  raiden-dapp/src/main.scss
  raiden-dapp/src/model/types.ts
  raiden-dapp/src/plugins/vuetify.ts
  raiden-dapp/src/scss/button.scss
  raiden-dapp/src/scss/colors.scss
  raiden-dapp/src/scss/dimensions.scss
  raiden-dapp/src/scss/input-screen.scss
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/src/views/Channels.vue
  raiden-dapp/src/views/Deposit.vue
  raiden-dapp/src/views/Divider.vue
  raiden-dapp/src/views/SelectHub.vue
  raiden-dapp/src/views/SelectToken.vue
  raiden-dapp/src/views/TokenInformation.vue
  raiden-dapp/tests/unit/components/address-input.spec.ts
  raiden-dapp/tests/unit/components/amount-input.spec.ts
  raiden-dapp/tests/unit/components/app-header.spec.ts
  raiden-dapp/tests/unit/components/channel-list.spec.ts
  raiden-dapp/tests/unit/components/confirmation-dialog.spec.ts
  raiden-dapp/tests/unit/components/tokens.spec.ts
  raiden-dapp/tests/unit/data/mock-data.ts
  raiden-dapp/tests/unit/views/channels.spec.ts
Labels: Dev: Please Review, dApp 📱

#210 Sdk init message
  raiden-dapp/src/components/NoAccessMessage.vue
  raiden-dapp/src/model/types.ts
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/tests/unit/components/no-access-message.spec.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
Labels: Dev: Please Review

#209 Send transfer
  raiden-dapp/src/components/Tokens.vue
  raiden-dapp/src/mixins/navigation-mixin.ts
  raiden-dapp/src/route-names.ts
  raiden-dapp/src/router.ts
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/src/views/SelectTarget.vue
  raiden-dapp/src/views/Transfer.vue
  raiden-dapp/tests/unit/components/mixins/navigation-mixin.spec.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
  raiden-dapp/tests/unit/views/deposit.spec.ts
  raiden-dapp/tests/unit/views/select-target.spec.ts
  raiden-dapp/tests/unit/views/select-token.spec.ts
  raiden-dapp/tests/unit/views/transfer.spec.ts
Labels: Dev: Please Review

#215 Use eslint-plugin-jsdoc to enforce JSDoc
  raiden/package-lock.json
  raiden/package.json
  raiden/src/channels/epics.ts
  raiden/src/messages/utils.ts
  raiden/src/raiden.ts
  raiden/src/store/epics.ts
  raiden/src/store/state.ts
  raiden/src/transfers/epics.ts
  raiden/src/transfers/reducer.ts
  raiden/src/transfers/utils.ts
  raiden/src/transport/epics.ts
  raiden/src/transport/reducer.ts
  raiden/src/transport/utils.ts
  raiden/src/utils/data.ts
  raiden/src/utils/ethers.ts
  raiden/src/utils/lru.ts
  raiden/src/utils/matrix.ts
  raiden/src/utils/redux.ts
  raiden/src/utils/rxjs.ts
  raiden/src/utils/types.ts
Labels: Dev: Please Review, sdk 🖥

#219 Adds information about signing matrix messages
  raiden-dapp/src/components/SplashScreen.vue
Labels: Dev: Please Review

#227 Extract text resources to locale json
  raiden-dapp/.env
  raiden-dapp/.eslintrc.js
  raiden-dapp/package-lock.json
  raiden-dapp/package.json
  raiden-dapp/src/App.vue
  raiden-dapp/src/components/AddressInput.vue
  raiden-dapp/src/components/AmountInput.vue
  raiden-dapp/src/components/AppHeader.vue
  raiden-dapp/src/components/ChannelActions.vue
  raiden-dapp/src/components/ChannelDeposit.vue
  raiden-dapp/src/components/ChannelLifeCycle.vue
  raiden-dapp/src/components/ChannelList.vue
  raiden-dapp/src/components/Confirmation.vue
  raiden-dapp/src/components/ConfirmationDialog.vue
  raiden-dapp/src/components/Divider.vue
  raiden-dapp/src/components/ErrorScreen.vue
  raiden-dapp/src/components/NoAccessMessage.vue
  raiden-dapp/src/components/ProgressOverlay.vue
  raiden-dapp/src/components/SplashScreen.vue
  raiden-dapp/src/components/TokenInformation.vue
  raiden-dapp/src/components/Tokens.vue
  raiden-dapp/src/i18n.ts
  raiden-dapp/src/locales/en.json
  raiden-dapp/src/main.ts
  raiden-dapp/src/mixins/navigation-mixin.ts
  raiden-dapp/src/model/types.ts
  raiden-dapp/src/route-names.ts
  raiden-dapp/src/router.ts
  raiden-dapp/src/views/About.vue
  raiden-dapp/src/views/Channels.vue
  raiden-dapp/src/views/OpenChannel.vue
  raiden-dapp/src/views/SelectHub.vue
  raiden-dapp/src/views/SelectToken.vue
  raiden-dapp/src/views/Transfer.vue
  raiden-dapp/tests/unit/app.spec.ts
  raiden-dapp/tests/unit/components/address-input.spec.ts
  raiden-dapp/tests/unit/components/amount-input.spec.ts
  raiden-dapp/tests/unit/components/app-header.spec.ts
  raiden-dapp/tests/unit/components/channel-deposit.spec.ts
  raiden-dapp/tests/unit/components/channel-lifecycle.spec.ts
  raiden-dapp/tests/unit/components/channel-list.spec.ts
  raiden-dapp/tests/unit/components/confirmation-dialog.spec.ts
  raiden-dapp/tests/unit/components/mixins/navigation-mixin.spec.ts
  raiden-dapp/tests/unit/components/no-access-message.spec.ts
  raiden-dapp/tests/unit/components/splash-screen.spec.ts
  raiden-dapp/tests/unit/components/tokens.spec.ts
  raiden-dapp/tests/unit/views/channels.spec.ts
  raiden-dapp/tests/unit/views/open-channel.spec.ts
  raiden-dapp/tests/unit/views/select-hub.spec.ts
  raiden-dapp/tests/unit/views/select-token.spec.ts
  raiden-dapp/tests/unit/views/transfer.spec.ts
  raiden-dapp/tsconfig.json
  raiden-dapp/vue.config.js
Labels: Dev: Please Review
