Repository raiden-network/light-client, pull requests merged in 2019-05, with the labels that each got.

#145 Adds handling of the shutdown event
  raiden-dapp/src/App.vue
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/src/store.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
  raiden-dapp/tests/unit/store.spec.ts
Labels: Dev: Please Review

#146 Adds token balance monitoring on new block
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
Labels: Dev: Please Review

#156 No access changes
  raiden-dapp/package-lock.json
  raiden-dapp/package.json
  raiden-dapp/src/App.vue
  raiden-dapp/src/components/NoAccessMessage.vue
  raiden-dapp/src/components/NoAccessScreen.vue
  raiden-dapp/src/components/NoValidProvider.vue
  raiden-dapp/src/components/SplashScreen.vue
  raiden-dapp/src/model/types.ts
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/src/views/Home.vue
  raiden-dapp/tests/unit/app.spec.ts
  raiden-dapp/tests/unit/components/no-access-message.spec.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
  raiden-dapp/tests/unit/store.spec.ts
  raiden-dapp/tests/unit/views/home.spec.ts
  raiden-dapp/vue.config.js
Labels: Dev: Please Review

#158 Adds support for goerli
  raiden/src/deployment/deployment_goerli.json
  raiden/src/raiden.ts
Labels: Dev: Please Review

#157 Adds a navigation guard on channel opening
  raiden-dapp/src/class-component-hooks.ts
  raiden-dapp/src/main.ts
  raiden-dapp/src/views/Deposit.vue
  raiden-dapp/tests/unit/views/deposit.spec.ts
Labels: Dev: Please Review

#163 Use npm link instead of sync-sdk.sh and split SDK build into esNext/commonjs
  .circleci/config.yml
  README.md
  raiden-dapp/.eslintignore
  raiden-dapp/.prettierignore
  raiden-dapp/package-lock.json
  raiden-dapp/package.json
  raiden-dapp/sync-sdk.sh
  raiden-dapp/tsconfig.json
  raiden/.gitignore
  raiden/package.json
  raiden/src/tsconfig.cjs.json
  raiden/src/tsconfig.json
  raiden/tsconfig.json
Labels: Dev: Please Review, enhancement

#164 Implement new channel deposit design
  raiden-dapp/src/components/AmountInput.vue
  raiden-dapp/src/components/ChannelDeposit.vue
  raiden-dapp/src/components/ChannelList.vue
  raiden-dapp/src/components/Confirmation.vue
  raiden-dapp/src/components/dialogs/DepositDialog.vue
  raiden-dapp/tests/unit/components/amount-input.spec.ts
  raiden-dapp/tests/unit/components/channel-deposit.spec.ts
  raiden-dapp/tests/unit/components/channel-list.spec.ts
Labels: Dev: Please Review

#166 Implements the select hub screen
  raiden-dapp/src/components/AddressInput.vue
  raiden-dapp/src/scss/input-screen.scss
  raiden-dapp/src/views/SelectHub.vue
  raiden-dapp/tests/unit/components/address-input.spec.ts
Labels: Dev: Please Review

#167 Implements the error screen and integrates it to open channel
  raiden-dapp/src/components/ErrorScreen.vue
  raiden-dapp/src/views/Deposit.vue
  raiden-dapp/tests/unit/views/deposit.spec.ts
Labels: Dev: Please Review

#169 Fix for settleChannel e2e tests timeout
  raiden/tests/e2e/raiden.spec.ts
Labels: Dev: Please Review, sdk 🖥
