Repository raiden-network/light-client, pull requests merged in 2020-03, with the labels that each got.

#1127 Dont distinct channel, only debounce, always send latest PFSCapacityUpdate
  raiden-ts/src/path/epics.ts
  raiden-ts/src/raiden.ts
Labels: sdk 🖥

#1140 Fix AddressInput value resetting when validation fails
  raiden-dapp/CHANGELOG.md
  raiden-dapp/src/components/AddressInput.vue
Labels: dApp 📱

#1165 Some improvements to bundle size
  raiden-dapp/vue.config.js
  raiden-ts/src/channels/epics.ts
  raiden-ts/src/epics.ts
  raiden-ts/src/helpers.ts
  raiden-ts/src/messages/utils.ts
  raiden-ts/src/path/epics.ts
  raiden-ts/src/path/utils.ts
  raiden-ts/src/raiden.ts
  raiden-ts/src/state.ts
  raiden-ts/src/transfers/epics/locked.ts
  raiden-ts/src/transfers/epics/refund.ts
  raiden-ts/src/transport/epics.ts
  raiden-ts/src/transport/utils.ts
  raiden-ts/src/types.ts
  raiden-ts/src/utils/actions.ts
  raiden-ts/src/utils/error.ts
  raiden-ts/src/utils/ethers.ts
  raiden-ts/src/utils/types.ts
Labels: optimization ⚡, sdk 🖥

#1107 Update Readme
  README.md
Labels: docs 📖
