Repository raiden-network/light-client, pull requests merged in 2020-06, with the labels that each got.

#1655 Support config.pfs=undefined as auto mode
  raiden-ts/CHANGELOG.md
  raiden-ts/src/services/epics.ts
Labels: sdk 🖥

#1679 Fix migration4 for oldChannels
  raiden-ts/src/migration/4.ts
  raiden-ts/src/state.ts
  raiden-ts/tests/unit/states/3_full.json
  raiden-ts/tests/unit/states/4_full.json
Labels: sdk 🖥

#1711 Implement payment routes
  raiden-cli/src/routes/payments.ts
  raiden-cli/src/types.ts
  raiden-cli/src/utils/payments.ts
  raiden-cli/src/utils/validation.ts
  raiden-ts/CHANGELOG.md
  raiden-ts/src/errors.json
  raiden-ts/src/raiden.ts
  raiden-ts/tests/e2e/raiden.spec.ts
Labels: cli, sdk 🖥

#1765 dapp: Fix non-informative error message on SDK's wrapped errors
  raiden-dapp/CHANGELOG.md
  raiden-dapp/src/services/raiden-service.ts
  raiden-dapp/tests/unit/raiden-service.spec.ts
Labels: dApp 📱

#1763 sdk: Fix waiting for failed deposit on Raiden.openChannel
  raiden-ts/CHANGELOG.md
  raiden-ts/src/raiden.ts
Labels: sdk 🖥

#1771 Try to fix base url for staging
  raiden-dapp/src/router/index.ts
Labels: dApp 📱, infrastructure 🚧

#1772 Fix staging deployment BASE_URL
  raiden-dapp/src/router/index.ts
  raiden-dapp/vue.config.js
Labels: dApp 📱, infrastructure 🚧

#1789 Use tar.gz build artifacts compatible with buster docker image
  .circleci/config.yml
  serve_pr/ci_dapp.sh
Labels: infrastructure 🚧

#1833 sdk: Fix nonce race when open+approve concurrently with Wallet
  raiden-ts/CHANGELOG.md
  raiden-ts/src/channels/epics.ts
  raiden-ts/tests/unit/epics/channels.spec.ts
Labels: sdk 🖥
