Repository raiden-network/light-client, pull requests merged in 2020-10, with the labels that each got.

#2187 dapp: add new feature - optional identifier query param in route
  raiden-dapp/CHANGELOG.md
  raiden-dapp/src/utils/query-params.ts
  raiden-dapp/src/views/TransferStepsRoute.vue
  raiden-dapp/tests/unit/query-params.spec.ts
  raiden-dapp/tests/unit/views/transfer-steps-route.spec.ts
Labels: dApp 📱, enhancement

#2214 dapp: fixes red underline under amount input fields
  raiden-dapp/CHANGELOG.md
  raiden-dapp/src/components/AmountInput.vue
Labels: dApp 📱

#2213 sdk: add 'execution reverted' to retriable channel errors
  raiden-ts/src/channels/utils.ts
Labels: sdk 🖥

#2225 sdk: improve default capability composition
  raiden-ts/src/epics.ts
  raiden-ts/tests/unit/epics/transport.spec.ts
  raiden-ts/tests/unit/mocks.ts
Labels: sdk 🖥

#2226 sdk: apply optional chaining operator only on optional properties
  raiden-ts/src/channels/epics.ts
  raiden-ts/src/channels/utils.ts
  raiden-ts/src/db/utils.ts
  raiden-ts/src/helpers.ts
  raiden-ts/src/persister.ts
  raiden-ts/src/raiden.ts
  raiden-ts/src/services/epics.ts
  raiden-ts/src/transfers/epics/locked.ts
  raiden-ts/src/transport/epics/helpers.ts
  raiden-ts/src/transport/epics/rooms.ts
  raiden-ts/src/transport/epics/webrtc.ts
Labels: refactor, sdk 🖥

#2249 deps: remove webpack as a direct dependency
  pnpm-lock.yaml
  raiden-dapp/package.json
Labels: dependencies

#2254 sdk: clean some matrix rtc monkeypatch and use same callID as PC
  raiden-ts/src/global.d.ts
  raiden-ts/src/polyfills.ts
  raiden-ts/src/transport/epics/webrtc.ts
Labels: sdk 🖥
